name: Check PR

on:
  pull_request_target:

jobs:
  check-sign-off:
    name: Write comment if unsigned commits found
    env:
      FORCE_COLOR: 1
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   pull-requests: write
    steps:
      - uses: live627/check-pr-signoff-action@v1